"""empty message

Revision ID: df4a62fa95fb
Revises: 7e6b8fa444d3
Create Date: 2023-04-05 00:37:03.325844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4a62fa95fb'
down_revision = '7e6b8fa444d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users', schema='main')
    op.drop_table('alembic_version', schema='main')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    schema='main'
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('salary', sa.INTEGER(), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='main'
    )
    # ### end Alembic commands ###
